[build]
  command = "npm run build"
  publish = "dist"

# Optionally, you can set env vars here, but it's better to set them in Netlify UI
# [build.environment]
#   VITE_SUPABASE_URL = "https://YOUR_PROJECT.supabase.co"
#   VITE_SUPABASE_ANON_KEY = "YOUR_ANON_KEY"


